###############################################################################
# Global configuration
###############################################################################

variables:
  # Just let the runner fetch and update the submodules for us.
  GIT_SUBMODULE_STRATEGY: normal
  I_AGREE_TO_ALLEGRO_EXPRESS_LICENSE: "yes"

# Split regression testing into a separate stage than upgrade tests. The
# upgrade tests tend to run slower and are generally less important than
# regression tests for most changes.
stages:
  - build
  - regression
  - upgrade

# This is needed otherwise the jobs won't always be added to MR pipelines. We
# can just say when: always because this is run as a child pipeline and only
# triggered under the desired conditions.
workflow:
  rules:
    - when: always

###############################################################################
# Build jobs
###############################################################################

Build ASDF:
  stage: build
  image: containers.common-lisp.net/cl-docker-images/sbcl:latest
  script:
    - make
  artifacts:
    when: always
    paths:
      - build/asdf.lisp

Build docs:
  stage: build
  image: buildpack-deps:buster
  script:
    - apt-get update
    - apt-get install -y --no-install-recommends texinfo texlive
    - make -C doc
  artifacts:
    when: always
    paths:
      - doc/asdf.html
      - doc/asdf.info
      - doc/asdf.pdf
      - doc/*.log

###############################################################################
# Regression tests
###############################################################################

.Regression test template:
  stage: regression
  image: containers.common-lisp.net/cl-docker-images/$l:$IMAGE_TAG
  variables:
    IMAGE_TAG: latest
  script:
    - export l=$l$variant
    - make
    - make test
  artifacts:
    when: always
    paths:
      - build/results/$l-test.text
  needs: []
  retry:
    max: 2
    when:
      - job_execution_timeout

Regression test:
  extends: .Regression test template
  parallel:
    matrix:
      - l: [abcl, allegro, ccl, clasp, clisp, cmucl, ecl, sbcl]
        IMAGE_TAG: latest
      - l: allegro
        IMAGE_TAG: latest
        variant: modern
      - l: abcl
        IMAGE_TAG: 1.7.1-jdk8

###############################################################################
# Upgrade tests
###############################################################################

.Upgrade test template:
  stage: upgrade
  image: containers.common-lisp.net/cl-docker-images/$l:$IMAGE_TAG
  variables:
    IMAGE_TAG: latest
  script:
    - export l=$l$variant
    - make
    - make test-upgrade
  artifacts:
    when: always
    paths:
      - build/results/$l-upgrade.text
  needs: []
  rules:
    - if: $RUN_UPGRADE_TESTS

Upgrade test:
  extends: .Upgrade test template
  parallel:
    matrix:
      - l: [allegro, ccl, clasp, clisp, ecl, sbcl]
        IMAGE_TAG: latest
      - l: allegro
        IMAGE_TAG: latest
        variant: modern

Upgrade test known failure:
  extends: .Upgrade test template
  parallel:
    matrix:
      # CMUCL fails due to CLOS bugs. 3.4 adds a new slot to SYSTEM, which
      # causes "Error in function KERNEL:CLASS-TYPEP: Class is currently
      # invalid: #<KERNEL::STANDARD-CLASS ASDF/SYSTEM:SYSTEM {60F43685}>"
      #
      # ABCL fails due to compiler macros being called for generic functions
      # locally declared NOTINLINE. See https://abcl.org/trac/ticket/487
      - l: [cmucl, abcl]
        IMAGE_TAG: latest
  allow_failure: true

.REQUIRE upgrade test template:
  extends: .Upgrade test template
  rules:
    - if: $RUN_UPGRADE_TESTS
      when: never
    - when: on_success

REQUIRE upgrade test:
  extends: .REQUIRE upgrade test template
  variables:
    ASDF_UPGRADE_TEST_TAGS: REQUIRE
  parallel:
    matrix:
      - l: [allegro, ccl, clisp, ecl, sbcl]
        IMAGE_TAG: latest
      - l: allegro
        IMAGE_TAG: latest
        variant: modern

REQUIRE upgrade test known failure:
  extends: .REQUIRE upgrade test template
  variables:
    ASDF_UPGRADE_TEST_TAGS: REQUIRE
  parallel:
    matrix:
      # CMUCL fails due to CLOS bugs. 3.4 adds a new slot to SYSTEM, which
      # causes "Error in function KERNEL:CLASS-TYPEP: Class is currently
      # invalid: #<KERNEL::STANDARD-CLASS ASDF/SYSTEM:SYSTEM {60F43685}>"
      - l: [cmucl]
      # ABCL fails due to compiler macros being called for generic functions
      # locally declared NOTINLINE. See https://abcl.org/trac/ticket/487
      - l: [abcl]
      - l: [clasp]
        IMAGE_TAG: latest
  allow_failure: true
